// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Properties.Model;

namespace PropertiesX.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190603234832_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Properties.Model.OtaAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParentId");

                    b.Property<int?>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OtaAmenity");
                });

            modelBuilder.Entity("Properties.Model.Property", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentVersion")
                        .IsRequired();

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersion");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Properties.Model.PropertyVersion", b =>
                {
                    b.Property<string>("Version")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("DescriptionId");

                    b.Property<int>("NameId");

                    b.Property<string>("Tenant")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Updated");

                    b.HasKey("Version");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("NameId");

                    b.ToTable("PropertyVersion");
                });

            modelBuilder.Entity("Properties.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DescriptionId");

                    b.Property<int?>("NameId");

                    b.Property<string>("PropertyVersionVersion");

                    b.Property<string>("RoomTypeId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("NameId");

                    b.HasIndex("PropertyVersionVersion");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Properties.Model.RoomType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DescriptionId");

                    b.Property<int>("NameId");

                    b.Property<string>("PropertyVersionVersion");

                    b.Property<string>("RoomTypeId");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("NameId");

                    b.HasIndex("PropertyVersionVersion");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("Properties.Model.Translations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Properties.Model.OtaAmenity", b =>
                {
                    b.HasOne("Properties.Model.RoomType", "Parent")
                        .WithMany("Amenities")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Properties.Model.Property", b =>
                {
                    b.HasOne("Properties.Model.PropertyVersion", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Properties.Model.PropertyVersion", b =>
                {
                    b.HasOne("Properties.Model.Translations", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("Properties.Model.Translations", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Properties.Model.ContactInfo", "ContactInfos", b1 =>
                        {
                            b1.Property<string>("PropertyVersionVersion");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20);

                            b1.HasKey("PropertyVersionVersion", "Id");

                            b1.ToTable("ContactInfo");

                            b1.WithOwner()
                                .HasForeignKey("PropertyVersionVersion");

                            b1.OwnsOne("Properties.Model.Address", "Address", b2 =>
                                {
                                    b2.Property<string>("ContactInfoPropertyVersionVersion");

                                    b2.Property<int>("ContactInfoId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("CityName")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.Property<string>("CountryName")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(50);

                                    b2.HasKey("ContactInfoPropertyVersionVersion", "ContactInfoId");

                                    b2.ToTable("ContactInfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPropertyVersionVersion", "ContactInfoId");

                                    b2.OwnsMany("Properties.Model.AddressLine", "Lines", b3 =>
                                        {
                                            b3.Property<string>("AddressContactInfoPropertyVersionVersion");

                                            b3.Property<int>("AddressContactInfoId");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Content")
                                                .IsRequired()
                                                .HasMaxLength(100);

                                            b3.Property<int>("LineNo");

                                            b3.Property<int>("ParentId");

                                            b3.HasKey("AddressContactInfoPropertyVersionVersion", "AddressContactInfoId", "Id");

                                            b3.ToTable("AddressLine");

                                            b3.WithOwner()
                                                .HasForeignKey("AddressContactInfoPropertyVersionVersion", "AddressContactInfoId");
                                        });
                                });

                            b1.OwnsMany("Properties.Model.PhoneInfo", "PhoneInfos", b2 =>
                                {
                                    b2.Property<string>("ContactInfoPropertyVersionVersion");

                                    b2.Property<int>("ContactInfoId");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(20);

                                    b2.HasKey("ContactInfoPropertyVersionVersion", "ContactInfoId", "Id");

                                    b2.ToTable("PhoneInfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPropertyVersionVersion", "ContactInfoId");
                                });
                        });

                    b.OwnsMany("Properties.Model.ImageLink", "Images", b1 =>
                        {
                            b1.Property<string>("PropertyVersionVersion");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Href")
                                .IsRequired()
                                .HasMaxLength(2000);

                            b1.Property<int>("SortValue");

                            b1.HasKey("PropertyVersionVersion", "Id");

                            b1.ToTable("ImageLink");

                            b1.WithOwner()
                                .HasForeignKey("PropertyVersionVersion");
                        });
                });

            modelBuilder.Entity("Properties.Model.Room", b =>
                {
                    b.HasOne("Properties.Model.Translations", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("Properties.Model.Translations", "Name")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.HasOne("Properties.Model.PropertyVersion", null)
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyVersionVersion");

                    b.HasOne("Properties.Model.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Properties.Model.RoomType", b =>
                {
                    b.HasOne("Properties.Model.Translations", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("Properties.Model.Translations", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Properties.Model.PropertyVersion", null)
                        .WithMany("RoomTypes")
                        .HasForeignKey("PropertyVersionVersion");

                    b.HasOne("Properties.Model.RoomType", null)
                        .WithMany("SubRooms")
                        .HasForeignKey("RoomTypeId");

                    b.OwnsMany("Properties.Model.ImageLink1", "Images", b1 =>
                        {
                            b1.Property<string>("RoomTypeId");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Href")
                                .IsRequired()
                                .HasMaxLength(2000);

                            b1.Property<int>("SortValue");

                            b1.HasKey("RoomTypeId", "Id");

                            b1.ToTable("ImageLink1");

                            b1.WithOwner()
                                .HasForeignKey("RoomTypeId");
                        });

                    b.OwnsMany("Properties.Model.RoomTag", "Tags", b1 =>
                        {
                            b1.Property<string>("RoomTypeId");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Tag")
                                .IsRequired();

                            b1.HasKey("RoomTypeId", "Id");

                            b1.ToTable("RoomTag");

                            b1.WithOwner()
                                .HasForeignKey("RoomTypeId");
                        });
                });

            modelBuilder.Entity("Properties.Model.Translations", b =>
                {
                    b.OwnsMany("Properties.Model.Translations+Pair", "Values", b1 =>
                        {
                            b1.Property<int>("TranslationsId");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("LanguageTag")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("TranslationsId", "Id");

                            b1.ToTable("Pair");

                            b1.WithOwner()
                                .HasForeignKey("TranslationsId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
